"""nullable desc in product

Revision ID: 5e3e69477225
Revises: 6605e5c977f1
Create Date: 2026-06-04 20:30:22.102253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e3e69477225"
down_revision: Union[str, Sequence[str], None] = "6605e5c977f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "description")
    # ### end Alembic commands ###
