"""remove desc in product

Revision ID: 6605e5c977f1
Revises: 6d2a2de09830
Create Date: 2026-06-04 20:27:55.500536

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6605e5c977f1"
down_revision: Union[str, Sequence[str], None] = "6d2a2de09830"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
