"""add stock to products

Revision ID: 6c6df3cbde06
Revises: fb29c112906a
Create Date: 2026-06-03 21:34:55.410007

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c6df3cbde06"
down_revision: Union[str, Sequence[str], None] = "fb29c112906a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "order_items", "products", ["product_id"], ["id"])
    op.add_column(
        "products",
        sa.Column("stock", sa.Integer(), nullable=False, server_default="100"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "stock")
    op.drop_constraint(None, "order_items", type_="foreignkey")
    # ### end Alembic commands ###
