"""add order tracking number

Revision ID: 6d2a2de09830
Revises: b483d56cf95d
Create Date: 2026-06-04 15:32:22.107676

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d2a2de09830"
down_revision: Union[str, Sequence[str], None] = "b483d56cf95d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("tracking_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "tracking_number")
    # ### end Alembic commands ###
