"""add image_id to products

Revision ID: 93cfc3fa556a
Revises: 6c6df3cbde06
Create Date: 2026-06-03 22:58:16.779305

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93cfc3fa556a"
down_revision: Union[str, Sequence[str], None] = "6c6df3cbde06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("image_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "image_id")
    # ### end Alembic commands ###
