"""add user profile fields

Revision ID: b483d56cf95d
Revises: 93cfc3fa556a
Create Date: 2026-06-04 12:18:31.842227

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b483d56cf95d"
down_revision: Union[str, Sequence[str], None] = "93cfc3fa556a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("users", sa.Column("address", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "address")
    op.drop_column("users", "phone")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
