"""add payment_settings table

Revision ID: ba10e0a37432
Revises: 8df2b5eedf2a
Create Date: 2026-06-06 23:33:34.491266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba10e0a37432"
down_revision: Union[str, Sequence[str], None] = "8df2b5eedf2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_name", sa.String(length=100), nullable=False),
        sa.Column("recipient", sa.String(length=100), nullable=False),
        sa.Column("card_number", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_settings")
    # ### end Alembic commands ###
